### ISSUE TITLE
1-org Project Factory preconditions Credential failure

### ISSUE THREAD

**Issue by paulwilljones** [terraform-google-modules/terraform-example-foundation#222]
Applying the `1-org` directory fails due to the project-factory preconditions failing to pick up credentials.

```
module.scc_notifications.module.project-factory.google_project.main: Creating...
module.org_secrets.module.project-factory.null_resource.preconditions (local-exec): Traceback (most recent call last):
module.org_secrets.module.project-factory.null_resource.preconditions (local-exec):   File "/home/.../repos/jetstack/terraform-enterprise-foundation/1-org/.terraform/modules/org_secrets/terraform-google-project-factory-8.1.0/modules/core_project_factory/scripts/preconditions/preconditions.py", line 492, in <module>
module.org_secrets.module.project-factory.null_resource.preconditions (local-exec):     retcode = main(sys.argv)
module.org_secrets.module.project-factory.null_resource.preconditions (local-exec):   File "/home/.../repos/jetstack/terraform-enterprise-foundation/1-org/.terraform/modules/org_secrets/terraform-google-project-factory-8.1.0/modules/core_project_factory/scripts/preconditions/preconditions.py", line 468, in main
module.org_secrets.module.project-factory.null_resource.preconditions (local-exec):     opts.impersonate_service_account)
module.org_secrets.module.project-factory.null_resource.preconditions (local-exec): TypeError: cannot unpack non-iterable Credentials object
```

```
Error: Error setting billing account "XXXXXX-XXXXXX-XXXXXX" for project "projects/prj-c-logging-f12b": googleapi: Error 400: Precondition check failed., failedPrecondition

  on .terraform/modules/org_audit_logs/terraform-google-project-factory-8.1.0/modules/core_project_factory/main.tf line 96, in resource "google_project" "main":
  96: resource "google_project" "main" {
```

## Steps to reproduce:

```
gcloud auth login
gcloud auth application-default login
cd 0-bootstrap
terraform apply -auto-approve
cd 1-org
terraform apply -auto-approve
```

**Comment by rjerrems** [comment]
Thanks for the report @paulwilljones - I am assuming some projects were created successfully? If so, it might be related to a quota error like reported here;

https://github.com/terraform-google-modules/terraform-example-foundation/issues/20

For instructions for increasing quota, see the docs here:

https://github.com/terraform-google-modules/terraform-example-foundation/tree/master/0-bootstrap#prerequisites

**Comment by rjerrems** [comment]
One other thing to check, is to make sure you are in the `group_org_admins` group referenced in the bootstrap step, as members of this group have access to impersonate the terraform service account which is used in the terraform provider configuration. (if not projects were successfully created)

**Comment by paulwilljones** [comment]
I think that's fixed, thanks.
